version: '3.3'
services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   platform: linux/x86_64
  #   working_dir: /app-frontend
  #   volumes:
  #     - ./frontend:/app-frontend
  #   depends_on:
  #     - backend
  # backend:
  #   container_name: app_backend
  #   build: ./backend
  #   ports:
  #     - 3001:3001
  #   platform: linux/x86_64
  #   volumes:
  #     - ./backend:/app-backend
  #   working_dir: /app-backend
  #   depends_on:
  #     - db
  #   environment:
  #     - APP_PORT=3001
  #     - JWT_SECRET=jwt_secret
  #     - DB_USER=root
  #     - DB_PASS=123456
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - NODE_ENV=development
  db:
    image: mysql:8.0.23
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      JWT_SECRET: secret
    restart: 'always'
    